#!/bin/bash
echo "------>> Install git"
echo "------>> Installing oh-my-zsh"
echo "------>> Install homebrew"
echo "------>> Install docker"
echo "------>> Install xcode-install"
echo "------>> Install rbenv"
echo "------>> Install nvm"
echo "------>> Install rust"
echo "------>> Install golang"
echo "------>> Install fzf"
echo "------>> Install obsidian"
echo "------>> Symlin config"
echo "❱ ln -s /Users/akshaybirajdar/personal-projects/Dotfiles/.common_conf.sh /Users/akshaybirajdar/.common_conf.sh"