name: Spec Runner

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-18.04
    container:
      image: ruby:2.6.5-stretch

    services:
      postgres:
        image: postgres:11.6-alpine
        ports: ["5432:5432"]
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      redis:
        image: redis
        ports:
        - 6379:6379
        options: --entrypoint redis-server

    steps:
    - uses: actions/checkout@v2

    # - name: Set up Ruby 2.6.5
    #   uses: actions/setup-ruby@v1
    #   with:
    #     ruby-version: 2.6.x

    - name: Install PostgreSQL 11 client
      run: |
        apt-get -yqq install libpq-dev

    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - name: Install Yarn
      run: |
        npm install yarn -g

    - name: Cahching Gems
      uses: actions/cache@v1
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gem-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gem-

    - name: Get yarn cache
      id: yarn-cache
      run: echo "::set-output name=dir::$(yarn cache dir)"

    - name: Caching Yarn
      uses: actions/cache@v1
      with:
        path: ${{ steps.yarn-cache.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-

    - name: Install gems & npm packages
      run: |
        gem install bundler -v 2.1.2
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3 --path vendor/bundle
        yarn install

    # - name: Install npm packages
    #   uses: borales/actions-yarn@v2.0.0
    #   with:
    #     cmd: install

    - name: Build App
      env:
        RAILS_ENV: test
        RAILS_MASTER_KEY: b12c24409a515434af5fefc50946b134
        DATABASE_URL: postgres://postgres:@postgres:5432/mvaahan_test
      run: |
        bin/setup
        bin/rails db:schema:load
        bin/rails db:migrate

    - name: Run Tests
      env:
        RAILS_ENV: test
        RAILS_MASTER_KEY: b12c24409a515434af5fefc50946b134
        DATABASE_URL: postgres://postgres:@postgres:5432/mvaahan_test
        DATABASE_CLEANER_ALLOW_REMOTE_DATABASE_URL: true
        redis_url: redis://redis:6379/0
      run: |
        bundle exec rspec spec/acceptance spec/models --order rand
